### ISSUE TITLE
play with time limit : when output best move ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#531]
how does time management work ?
all engines seem to know when to give a best move (which will stop their clock).
but how / when does it decide to stop the search and output a "best move" ?

i'm testing several UCI engines with the CuteChess GUI (on Linux), mostly setting a time-per-game of 10 or 12 minutes (plus some bonus sec). Within an amount of seconds, all engines reach a different depth, according to their processing speed : maybe the engine calculates / decides that a next depth would take too long, regarding the time-per-game .. i don't know how your engine decides that - and does it differ from the way other engines do it ?

maybe an engine can also take a certain position type in consideration, eg. one with possible tactics by sacrifices and/or a "closed centre" (by stucked pawns) .. maybe it uses several search types depending on the position(type) and play time - i'm not refering to "personalities" like Rodent has, i only wonder about time management.

**Comment by TerjeKir** [comment]
The most basic time management scheme is something like "think until we have spent 1/30th of the available time". When the time is up the current depth is aborted and the bestmove of the previous depth is output. This is commonly seen in weaker engines.

An obvious issue with the above naive approach is that all the time spent during the depth that is aborted is mostly wasted as it has no bearing on the chosen move for this turn. So one of the goals when trying to improve on this version is to avoid wasting time in this way. One approach is trying to estimate the time the next depth will take to finish given stats from the previous depth(s), and not starting if this would exceed the time limit. Another is to make 2 time limits, one being a limit for starting the next depth, and the other being similar to the naive approach's limit where we give up finishing and abort the current depth.

Weiss uses the latter, making a limit for starting the next depth based on current time left, increment, and moves to go until next time control (if applicable), and setting the hard limit for aborting to be 5 times as long as the first.

In addition to attempting to avoid wasting time on depths that won't finish, there are many other considerations - saving too much time for the lategame is pointless if we are lost before getting there due to spending too little, time spent on obvious or forced moves is wasted, and if the score is starting to drop it may be worth it to spend more time to figure out how bad it's getting and hopefully finding a better alternative before it's too late. The first of these is already taken care of even in the naive version by deciding usage relative to the time available (1/30th or similar) which will spend a lot of time early and then gradually less and less each turn as the time available diminishes.

If a depth finishes with a different bestmove than the previous one, Weiss will ignore the limit for starting the next depth as it seems to be a difficult decision and worth spending more time on. Weiss doesn't do anything regarding falling eval.

Stockfish recently tried using a neural network given features of the position (piece counts or such, I don't remember) to decide on the time limits, but while it was slightly better at very short time controls (10 seconds per game), it didn't gain anything at longer time controls and was discarded I think.

**Comment by tissatussa** [comment]
thanks for this reply !  It has everything i wanted to know, esp. "..using a neural network given features of the position.." is interesting !  At least the SF developers tried .. Do you know of other engines that try to determine _features of the position_ -- maybe not related to time management ?

**Comment by TerjeKir** [comment]
I believe that is the main idea of [Shashchess](https://github.com/amchess/ShashChess), a Stockfish fork that uses different 'personalities' for different positions. I know nothing of the details, though, so I can't speak to which features it looks for nor what it changes based on them.

**Comment by tissatussa** [comment]
yeah, i know ShashChess, for a while it was my "favorite" engine, so to speak .. but i didn't see the connection to my time management question .. until now ! So thanks, maybe i'll contact them and share my ideas !
