### ISSUE TITLE
improvements = new version ?

### ISSUE THREAD

**Issue by tissatussa** [TerjeKir/weiss#700]
hi, for a rather long time i follow your PR's and versions .. the master version is still being called v2.1-dev but i see many changes lately .. will your new code result in a v2.2 soon ?

**Comment by TerjeKir** [comment]
I am choosing not to release a new official version for the time being due to the state of the chess engine rating lists. Most of them list (and even still test with) known clones like Houdini and Fire among other things. I prefer not to have Weiss take any part in that.

The main tournaments compile the newest version of Weiss anyway so what you see at TCEC and Chess.com is up to date with all my latest changes :)
